# Generated by Django 2.2.7 on 2019-11-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile-image/avatar.jpg', upload_to='profile-image/'),
        ),
    ]
