# Generated by Django 2.2.7 on 2019-11-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191108_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='profile-image/avatar.jpg', upload_to='profile-image/'),
        ),
    ]
