# Generated by Django 2.2.7 on 2019-11-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191108_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile-image/avatar.jpg', upload_to='profile-image/'),
        ),
    ]
